import Head from 'next/head';
import { useState } from 'react';
import axios from 'axios';
import { useRouter } from 'next/router';
const Auth = () => {
	const [username, handleUsername] = useState<String>('');
	const [password, handlePassword] = useState<String>('');
	const router = useRouter();
	const validateForm = async () => {
		if (username.length >= 0 || password.length >= 0) {
			try {
				const response = await axios.post('http://localhost:8080/auth/login/', {
					username,
					password,
				});
				if (!response?.data?.message) return false;
				console.log(response.data.message);
			} catch (error: any) {
				if (error?.response?.data?.message) {
					return console.log(
						'A login error has been appeared: ' + error?.response?.data?.message
					);
				}
			}
		}

		return false;
	};

	return (
		<>
			<Head>
				<title>Guttmann</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<button
				onClick={() => {
					router.push('/games/wordgame');
				}}
			>
				{' '}
				Ir al juego{' '}
			</button>
			<div className="w-full max-w-xs center-screen">
				<form className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
					<div className="mb-4">
						<label className="block text-gray-700 text-sm font-bold mb-2">
							Username
						</label>
						<input
							onChange={(e) => handleUsername(e.target.value)}
							className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
							id="text"
							type="text"
							placeholder="Username"
						/>
					</div>
					<div className="mb-6">
						<label className="block text-gray-700 text-sm font-bold mb-2">
							Password
						</label>
						<input
							onChange={(e) => handlePassword(e.target.value)}
							className="shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
							id="password"
							type="password"
							placeholder="******************"
						/>
						<p className="text-red-500 text-xs italic">Please choose a password.</p>
					</div>

					<div className="flex items-center justify-between">
						<button
							className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
							type="button"
							onClick={() => validateForm()}
						>
							Login
						</button>

						<a
							className="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800"
							href="#"
						>
							Forgot Password?
						</a>
					</div>
				</form>

				<p className="text-center text-gray-500 text-xs">
					&copy;2020 Guttmann, all rights reserved.
				</p>
			</div>
		</>
	);
};

export default Auth;
