import Head from 'next/head';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import axios, { AxiosResponse } from 'axios';

export default function Home() {
	const router = useRouter();
	const [auth, setAuth] = useState();
	// useEffect(() => {
	// 	if (!auth) {
	// 		router.push('/auth');
	// 	}
	// }, []);

	useEffect(() => {
		axios
			.get('http://localhost:8080/home')
			.then((response: AxiosResponse) => {
				console.log('Staying');
			})
			.catch((error) => {
				console.log('Leaving');
				router.push('/auth');
			});
	}, []);

	return (
		<>
			<Head>
				<title>Guttmann</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<button
				onClick={() => {
					router.push('/games/wordgame');
				}}
			>
				Ir al juego
			</button>
		</>
	);
}
