import Head from 'next/head';
import { useState, useEffect } from 'react';
import userState from '../utils/state';
import { useRouter } from 'next/router';

export default function Home() {
	const router = useRouter();
	const auth = userState((state: any) => state.isLogged);

	// useEffect(() => {
	// 	if (!auth) {
	// 		router.push('/auth');
	// 	}
	// }, []);

	return (
		<>
			<Head>
				<title>Guttmann</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<button
				onClick={() => {
					router.push('/games/wordgame');
				}}
			>
				{' '}
				Ir al juego{' '}
			</button>
		</>
	);
}
