import Head from "next/head";
import { useState, useEffect } from "react";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "./styles/Home.module.css";
import GameConfigForm from "../../../components/gameConfigForm/index"
export default function Home() {


  return (
    <>
      <Head>
        <title>Guttmann</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <GameConfigForm></GameConfigForm>
    </>
  );
}
